build:
  version: "1.0"

cards:
  message: "Welcome to JagadeeshBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@jagadeeshbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721