build:
  version: "2.0"

loans:
  message: "Welcome to JagadeeshBank loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@jagadeeshbank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467